{% set name = "mockito" %}
{% set version = "1.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kaste/mockito-python/archive/{{ version }}.tar.gz
  sha256: 6544f65d750d2243020a98ac9d139ed6b10a934a3a6eb4caa56542062107d4af

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5

test:
  imports:
    - mockito
  requires:
    - pip
    - pytest
    - numpy
  source_files:
    - tests/
  commands:
    - pip check
    - pytest tests

about:
  home: https://github.com/kaste/mockito-python
  summary: Spying framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vnlitvinov
